# Generated by Django 3.1.3 on 2020-11-26 21:59

from django.db import migrations, models
import django.db.models.deletion
import shopping_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('access_code', models.CharField(default=shopping_list.models.gen_access_code, max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=200)),
                ('is_bought', models.BooleanField(blank=True, default=False, null=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist')),
            ],
        ),
    ]
